### ISSUE TITLE
Error thrown when accessing skills on hunter class

### ISSUE THREAD

**Issue by Eutropios** [pozgerab/WynnBuild#1]
On hunter class, and on hunter class only, when you open the compass to view the skill loadout, the game crashes due an `IllegalArgumentError`.
<details>
    <summary>Relevant Stackrace:</summary>

```java
[15:42:02] [Render thread/ERROR]: Unreported exception thrown!
java.lang.IllegalArgumentException: No enum constant com.gertoxq.quickbuild.Cast.HUNTER
	at java.lang.Enum.valueOf(Enum.java:273) ~[?:?]
	at com.gertoxq.quickbuild.Cast.valueOf(Cast.java:3) ~[WynnBuild-v0.2.4.1.1+1.20.2.jar:?]
	at com.gertoxq.quickbuild.screens.CharacterInfoScreen.getCast(CharacterInfoScreen.java:41) ~[WynnBuild-v0.2.4.1.1+1.20.2.jar:?]
	at com.gertoxq.quickbuild.client.QuickBuildClient.saveCharInfo(QuickBuildClient.java:166) ~[WynnBuild-v0.2.4.1.1+1.20.2.jar:?]
	at com.gertoxq.quickbuild.client.QuickBuildClient.lambda$onInitializeClient$3(QuickBuildClient.java:95) ~[WynnBuild-v0.2.4.1.1+1.20.2.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:102) ~[client-intermediary.jar:?]
	at com.gertoxq.quickbuild.util.Task.lambda$init$0(Task.java:40) ~[WynnBuild-v0.2.4.1.1+1.20.2.jar:?]
	at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
	at com.gertoxq.quickbuild.util.Task.lambda$init$1(Task.java:38) ~[WynnBuild-v0.2.4.1.1+1.20.2.jar:?]
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:43) ~[fabric-lifecycle-events-v1-2.2.2+c8b10480a0-cce012c5defdfdc0.jar:?]
	at net.minecraft.class_310.handler$zfk000$fabric-lifecycle-events-v1$onEndTick(class_310.java:4606) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java:2007) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1237) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:856) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:253) ~[minecraft-1.20.2-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.11.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[NewLaunch.jar:?]
[15:42:03] [Render thread/INFO]: Stopping worker threads
[15:42:03] [pool-74-thread-1/ERROR]: Tried to send packet: "class_2805", but connection was null.
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 2024-05-26 15:42:03
Description: Unexpected error

java.lang.IllegalArgumentException: No enum constant com.gertoxq.quickbuild.Cast.HUNTER
	at java.base/java.lang.Enum.valueOf(Enum.java:273)
	at com.gertoxq.quickbuild.Cast.valueOf(Cast.java:3)
	at com.gertoxq.quickbuild.screens.CharacterInfoScreen.getCast(CharacterInfoScreen.java:41)
	at com.gertoxq.quickbuild.client.QuickBuildClient.saveCharInfo(QuickBuildClient.java:166)
	at com.gertoxq.quickbuild.client.QuickBuildClient.lambda$onInitializeClient$3(QuickBuildClient.java:95)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at com.gertoxq.quickbuild.util.Task.lambda$init$0(Task.java:40)
	at java.base/java.util.HashMap.forEach(HashMap.java:1421)
	at com.gertoxq.quickbuild.util.Task.lambda$init$1(Task.java:38)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:43)
	at net.minecraft.class_310.handler$zfk000$fabric-lifecycle-events-v1$onEndTick(class_310.java:4606)
	at net.minecraft.class_310.method_1574(class_310.java:2007)
	at net.minecraft.class_310.method_1523(class_310.java:1237)
	at net.minecraft.class_310.method_1514(class_310.java:856)
	at net.minecraft.client.main.Main.main(Main.java:253)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.base/java.lang.Enum.valueOf(Enum.java:273)
	at com.gertoxq.quickbuild.Cast.valueOf(Cast.java:3)
	at com.gertoxq.quickbuild.screens.CharacterInfoScreen.getCast(CharacterInfoScreen.java:41)
	at com.gertoxq.quickbuild.client.QuickBuildClient.saveCharInfo(QuickBuildClient.java:166)
	at com.gertoxq.quickbuild.client.QuickBuildClient.lambda$onInitializeClient$3(QuickBuildClient.java:95)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at com.gertoxq.quickbuild.util.Task.lambda$init$0(Task.java:40)
	at java.base/java.util.HashMap.forEach(HashMap.java:1421)
	at com.gertoxq.quickbuild.util.Task.lambda$init$1(Task.java:38)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:43)
	at net.minecraft.class_310.handler$zfk000$fabric-lifecycle-events-v1$onEndTick(class_310.java:4606)
```
</details>
If a full stacktrace is desired, it can be found here: https://gist.github.com/Eutropios/03237a0b30b2d33ce3d4b525bf175949

**Comment by Eutropios** [comment]
After a little digging, it appears the error occurs in [quickbuild/Cast.java](https://github.com/pozgerab/WynnBuild/blob/main/src/main/java/com/gertoxq/quickbuild/Cast.java), where the upgraded classes are not present.

**Comment by pozgerab** [comment]
Thank you for reporting this, I implemented upgraded classes. The knight class not being affected is probably something with Wynncraft as I didn't think of upgraded classes sooner. Thanks for pointing this out!

**Comment by Eutropios** [comment]
You're welcome!! Thanks for the fix! 😄
